"""Grounded answer generation based on the structured intent result."""

from __future__ import annotations

import json
import os
from typing import Any

import httpx
from pydantic import BaseModel

from config.settings import api_key_is_missing, load_project_env


class GroundedAnswerResult(BaseModel):
    """Record whether the final answer was generated by a model or a fallback."""

    answer: str
    used_model: bool = False
    model_name: str | None = None
    fallback_reason: str | None = None


def compose_grounded_answer(
    *,
    user_message: str,
    deterministic_answer: str,
    intent_result: Any,
    http_client: httpx.Client | None = None,
    api_key: str | None = None,
    base_url: str | None = None,
    model: str | None = None,
) -> GroundedAnswerResult:
    """Generate a constrained answer and safely fall back on model failure."""

    load_project_env()
    if os.getenv("AGENT_DISABLE_LLM") == "1" and http_client is None:
        return GroundedAnswerResult(answer=deterministic_answer, fallback_reason="model_disabled")

    resolved_api_key = api_key if api_key is not None else os.getenv("AGENT_OPENAI_API_KEY")
    if api_key_is_missing(resolved_api_key):
        return GroundedAnswerResult(answer=deterministic_answer, fallback_reason="model_config_missing")

    resolved_base_url = (base_url or os.getenv("AGENT_OPENAI_BASE_URL", "https://api.siliconflow.cn/v1")).rstrip("/")
    resolved_model = model or os.getenv("AGENT_OPENAI_MODEL", "Qwen/Qwen3-8B")
    payload = {
        "user_message": user_message,
        "intent_result": intent_result.model_dump() if hasattr(intent_result, "model_dump") else intent_result,
        "fallback_answer": deterministic_answer,
        "service_boundary": "当前只完成粗意图识别，不能承诺订单、规则、退款、赔偿或人工流转结果。",
    }
    request_kwargs = {
        "headers": {"Authorization": f"Bearer {resolved_api_key}", "Content-Type": "application/json"},
        "json": {
            "model": resolved_model,
            "messages": [
                {
                    "role": "system",
                    "content": (
                        "你是电商平台客服 Agent。只能根据结构化 intent_result 和服务边界回复；"
                        "不得编造订单、物流、活动规则、退款资格、赔偿或人工流转结果。"
                    ),
                },
                {"role": "user", "content": json.dumps(payload, ensure_ascii=False)},
            ],
            "temperature": 0.2,
        },
    }

    try:
        if http_client is not None:
            response = http_client.post(f"{resolved_base_url}/chat/completions", **request_kwargs)
        else:
            response = httpx.post(f"{resolved_base_url}/chat/completions", **request_kwargs, timeout=30)
        response.raise_for_status()
        answer = response.json()["choices"][0]["message"]["content"].strip()
        if not answer:
            return GroundedAnswerResult(
                answer=deterministic_answer,
                model_name=resolved_model,
                fallback_reason="empty_model_answer",
            )
        return GroundedAnswerResult(answer=answer, used_model=True, model_name=resolved_model)
    except (httpx.HTTPError, KeyError, IndexError, TypeError, ValueError) as exc:
        return GroundedAnswerResult(
            answer=deterministic_answer,
            model_name=resolved_model,
            fallback_reason=exc.__class__.__name__,
        )
